config/routes.rb
Rails.application.routes.draw do
  resources :conversions
  root to: 'conversions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversion.rb
class Conversion < ApplicationRecord
  validates :convert_from, :convert_to, presence: true, length: { is: 3 }, allow_blank: false
  before_save :uppercase_currency

  TIMEZONE = 'Australia/Sydney'.freeze

  def uppercase_currency
    convert_from.upcase!
    convert_to.upcase!
  end
  
  def self.target_currencies
    self.distinct.pluck(:convert_to) | self.distinct.pluck(:convert_from)
  end

  def updateRateValue(curFromEurRate, curToEurRate, timestamp)
    if curFromEurRate.present? && curToEurRate.present?
      curFromEurVal = 1.0 / curFromEurRate
      newRate = curFromEurVal * curToEurRate
      update_attribute(:rate, newRate)
    end 
    update_attribute(:fetch_time, Time.at(timestamp).in_time_zone(TIMEZONE))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController
  def index
    @conversions = Conversion.all
    @fetch_time = Conversion.first.try(:fetch_time)
    @error_message = session[:error_message]
    session[:error_message] = nil
  end

  def new
    redirect_to conversions_path
  end

  def create
    @conversion = Conversion.new(conversion_params)
    begin
      @conversion.save
    rescue ActiveRecord::RecordNotUnique
      error_message = "Error saving #{@conversion.convert_from} - #{@conversion.convert_to}. Conversion pair already existing."
      session[:error_message] = error_message
    end
    redirect_to conversions_path
  end

  def show
    redirect_to conversions_path
  end

  def destroy
    @conversion = Conversion.find(params[:id])
    @conversion.destroy
    redirect_to conversions_path
  end

  private
    def conversion_params
      params.require(:conversion).permit(:convert_from, :convert_to)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversions_helper.rb
module ConversionsHelper

  PRECISION = 3.freeze

  def get_rate_text(rate)
    rate > 0 ? rate.round(PRECISION) : 'No data for this conversion pair'
  end

  def format_fetch_time(fetch_time)
    I18n.l(fetch_time.in_time_zone('Australia/Sydney'), format: :long)
  end
end

app/views/conversions/_add_conversion_form.html.erb
<%= form_with scope: :conversion, local: true do |form| %>
  <tr>
    <td><%= form.text_field :convert_from %></td>
    <td><%= form.text_field :convert_to %></td>
    <td></td>
    <td><%= form.submit "SAVE" %></td>
  </tr>
<% end %>

app/views/conversions/_conversions_table.html.erb
<tr>
  <th>Currency 1</th>
  <th>Currency 2</th>
  <th>Rate</th>
  <th></th>
</tr>

<% conversions.each do |conversion| %>
  <tr>
    <td><%= conversion.convert_from %></td>
    <td><%= conversion.convert_to %></td>
    <td><%= get_rate_text(conversion.rate) %></td>
    <td><%= link_to '<Remove>', conversion_path(conversion), method: :delete %></td>
  </tr>
<% end %>

app/views/conversions/_error_block.html.erb
<% if error_message %>
  <div id = "error_block">
    <strong><%= error_message %></strong>
  </div>
<% end %>

app/views/conversions/_fetch_time_block.html.erb
<% if fetch_time %>
  <div id = "fetch_time_block">
    Rates as of <strong><%= format_fetch_time(fetch_time) %></strong>
  </div>
<% end %>

app/views/conversions/index.html.erb
<h1>Currency Conversions</h1>

<%= render partial: 'error_block', locals: { error_message: @error_message } %>

<%= render partial: 'fetch_time_block', locals: { fetch_time: @fetch_time } %>

<table>
  <%= render partial: 'conversions_table', locals: { conversions: @conversions } %>
  <%= render partial: 'add_conversion_form' %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrecyConversions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>